<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useAdminUsersStore } from '@/stores/adminUsers'
import { formatDateTime, formatPrice } from '@/utils/display'

const auth = useAuthStore(); const store = useAdminUsersStore()
const filters = reactive({ query: '', role: '', isActive: '' }); const edit = ref(null); const balance = ref(null); const password = ref('')
const notice = ref({ type: '', text: '' }); let timer
const roles = [{ value: '', label: '全部角色' }, { value: 'USER', label: '用户' }, { value: 'BOOSTER', label: '打手' }, { value: 'ADMIN', label: '管理员' }]
function flash(type, text) { notice.value = { type, text }; clearTimeout(timer); timer = setTimeout(() => { notice.value.text = '' }, 3500) }
function load(page = 1) { return store.fetchUsers({ page, query: filters.query.trim(), role: filters.role, isActive: filters.isActive }) }
watch(() => [filters.role, filters.isActive], () => load(1))
async function openEdit(user) { const result = await store.getUser(user.id); const detail = result.success ? result.data : user; edit.value = { ...detail, phone: detail.phone || '', bio: detail.bio || '' }; if (!result.success) flash('error', result.error) }
async function saveEdit() { const { id, username, phone, bio, is_verified, booster_quota } = edit.value; const r = await store.updateUser(id, { username, phone: phone || null, bio: bio || null, is_verified, booster_quota: Number(booster_quota) }); if (r.success) { edit.value = null; flash('success', '用户资料已更新') } else flash('error', r.error) }
function strongPassword() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'; let value = 'Aa1'; for (let i = 3; i < 14; i++) value += chars[Math.floor(Math.random() * chars.length)]; return value }
async function resetPassword(user) { password.value = strongPassword(); const r = await store.resetPassword(user.id, password.value); password.value = ''; flash(r.success ? 'success' : 'error', r.success ? '密码已重置' : r.error) }
async function toggle(user) { const r = await store.setStatus(user.id, !user.is_active); flash(r.success ? 'success' : 'error', r.success ? '状态已更新' : r.error) }
function openBalance(user) { balance.value = { user, amount: '', reason: '' } }
async function saveBalance() { const r = await store.adjustBalance(balance.value.user.id, balance.value.amount, balance.value.reason.trim()); if (r.success) { balance.value = null; await load(store.pagination.page); flash('success', '余额已调整') } else flash('error', r.error) }
onMounted(load)
</script>
<template>
  <section v-if="auth.isAdmin" class="surface-card p-4 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row"><input v-model="filters.query" class="input min-h-[44px] flex-1" placeholder="搜索用户名或邮箱" @keyup.enter="load(1)" /><select v-model="filters.role" class="input min-h-[44px]"><option v-for="o in roles" :key="o.value" :value="o.value">{{ o.label }}</option></select><select v-model="filters.isActive" class="input min-h-[44px]"><option value="">全部状态</option><option :value="true">启用</option><option :value="false">禁用</option></select><button class="btn-primary min-h-[44px] !px-5" @click="load(1)">搜索</button></div>
    <div v-if="notice.text" class="mt-4" :class="notice.type === 'success' ? 'message-success' : 'message-error'">{{ notice.text }}</div>
    <div class="mt-5 overflow-x-auto"><table class="min-w-[1120px] w-full text-left text-sm"><thead class="bg-surface-2 text-ink-2"><tr><th class="p-3">ID</th><th class="p-3">用户</th><th class="p-3">邮箱</th><th class="p-3">角色</th><th class="p-3">状态</th><th class="p-3">可用余额</th><th class="p-3">冻结</th><th class="p-3">累计收入</th><th class="p-3">累计提现</th><th class="p-3">注册时间</th><th class="p-3">操作</th></tr></thead><tbody><tr v-for="user in store.users" :key="user.id" class="border-t border-line-1 text-ink-1"><td class="p-3">{{ user.id }}</td><td class="p-3 font-medium">{{ user.username }}</td><td class="p-3">{{ user.email }}</td><td class="p-3">{{ user.role }}</td><td class="p-3"><span :class="user.is_active ? 'badge-approved' : 'badge-cancelled'">{{ user.is_active ? '启用' : '禁用' }}</span></td><td class="p-3">{{ formatPrice(user.wallet?.available) }}</td><td class="p-3">{{ formatPrice(user.wallet?.frozen) }}</td><td class="p-3">{{ formatPrice(user.wallet?.total_income) }}</td><td class="p-3">{{ formatPrice(user.wallet?.total_withdrawn) }}</td><td class="p-3">{{ formatDateTime(user.created_at) }}</td><td class="p-3"><div class="flex gap-2"><button class="btn-ghost min-h-[44px] !px-3" @click="openEdit(user)">编辑</button><button class="btn-ghost min-h-[44px] !px-3" @click="resetPassword(user)">重置密码</button><button class="btn-secondary min-h-[44px] !px-3" @click="toggle(user)">{{ user.is_active ? '禁用' : '启用' }}</button><button class="btn-secondary min-h-[44px] !px-3" @click="openBalance(user)">调余额</button></div></td></tr></tbody></table></div>
    <div v-if="!store.loading && !store.users.length" class="empty-state mt-6">暂无用户</div><div v-if="store.pagination.pages > 1" class="mt-5 flex items-center justify-between"><span class="text-sm text-ink-2">第 {{ store.pagination.page }} / {{ store.pagination.pages }} 页，共 {{ store.pagination.total }} 人</span><div class="flex gap-2"><button class="btn-secondary min-h-[44px] !px-4" :disabled="store.pagination.page <= 1" @click="load(store.pagination.page - 1)">上一页</button><button class="btn-secondary min-h-[44px] !px-4" :disabled="store.pagination.page >= store.pagination.pages" @click="load(store.pagination.page + 1)">下一页</button></div></div>
    <div v-if="edit || balance" class="modal-scrim"><div class="modal-card w-full max-w-lg p-6"><form v-if="edit" class="space-y-4" @submit.prevent="saveEdit"><h3 class="text-xl font-semibold text-ink-1">编辑用户</h3><input v-model="edit.username" class="input" placeholder="用户名" /><input v-model="edit.phone" class="input" placeholder="手机号" /><textarea v-model="edit.bio" class="input" rows="3" placeholder="简介" /><label class="flex min-h-[44px] items-center gap-2 text-ink-2"><input v-model="edit.is_verified" type="checkbox" /> 已认证</label><input v-model.number="edit.booster_quota" type="number" min="0" max="50" class="input" placeholder="打手名额" /><div class="flex justify-end gap-2"><button type="button" class="btn-ghost min-h-[44px]" @click="edit=null">取消</button><button class="btn-primary min-h-[44px]">保存</button></div></form><form v-else class="space-y-4" @submit.prevent="saveBalance"><h3 class="text-xl font-semibold text-ink-1">调整余额</h3><p class="text-sm text-ink-2">{{ balance.user.username }}：正数充值，负数扣减</p><input v-model="balance.amount" required type="number" step="0.01" class="input" placeholder="金额" /><input v-model="balance.reason" required class="input" placeholder="原因" /><div class="flex justify-end gap-2"><button type="button" class="btn-ghost min-h-[44px]" @click="balance=null">取消</button><button class="btn-primary min-h-[44px]">提交</button></div></form></div></div>
  </section>
</template>
