<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useSiteStore } from '@/stores/site'
const store = useSiteStore(); const form = reactive({ site_name: '', site_description: '' }); const file = ref(null); const notice = ref({ type: '', text: '' })
function sync() { form.site_name = store.settings.site_name; form.site_description = store.settings.site_description || '' }
async function save() { const r = await store.updateSettings({ site_name: form.site_name.trim(), site_description: form.site_description.trim() || null }); notice.value = r.success ? { type: 'success', text: '站点设置已保存' } : { type: 'error', text: r.error }; if (r.success) sync() }
async function upload() { if (!file.value) return; const r = await store.uploadLogo(file.value); notice.value = r.success ? { type: 'success', text: 'Logo 已上传，品牌已刷新' } : { type: 'error', text: r.error }; file.value = null }
async function remove() { const r = await store.removeLogo(); notice.value = r.success ? { type: 'success', text: 'Logo 已删除' } : { type: 'error', text: r.error } }
onMounted(async () => { await store.fetchSettings(); sync() })
</script>
<template><section class="surface-card p-4 sm:p-6"><h2 class="text-2xl font-semibold text-ink-1">站点管理</h2><p class="mt-2 text-sm text-ink-2">维护平台对外展示的名称、简介与品牌 Logo。</p><div v-if="notice.text" class="mt-4" :class="notice.type === 'success' ? 'message-success' : 'message-error'">{{ notice.text }}</div><form class="mt-6 grid max-w-2xl gap-5" @submit.prevent="save"><div><label class="label" for="site-name">站点名称</label><input id="site-name" v-model="form.site_name" required maxlength="200" class="input min-h-[44px]" /></div><div><label class="label" for="site-description">站点简介</label><textarea id="site-description" v-model="form.site_description" maxlength="5000" rows="4" class="input resize-none"></textarea></div><div class="flex flex-wrap items-center gap-3"><button class="btn-primary min-h-[44px] !px-5" :disabled="store.loading">保存设置</button></div></form><div class="mt-8 border-t border-line-1 pt-6"><label class="label" for="site-logo">站点 Logo</label><div v-if="store.settings.site_logo_url" class="mb-4 flex items-center gap-4"><img :src="store.settings.site_logo_url" class="h-20 w-20 rounded-card object-cover" alt="站点 Logo" /><button type="button" class="btn-danger min-h-[44px] !px-4" @click="remove">删除 Logo</button></div><input id="site-logo" type="file" accept="image/png,image/jpeg,image/webp" class="input min-h-[44px]" @change="file = $event.target.files?.[0] || null" /><button type="button" class="btn-secondary mt-3 min-h-[44px] !px-5" :disabled="!file || store.loading" @click="upload">上传 Logo</button><p class="mt-2 text-xs text-ink-3">推荐 512×512px PNG，透明背景，≤10MB。</p></div></section></template>
